# Generated by Django 2.2.15 on 2020-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='votes',
            field=models.CharField(default=None, max_length=225),
        ),
    ]
