# Generated by Django 2.2.15 on 2020-08-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='votes',
        ),
        migrations.AddField(
            model_name='product',
            name='novote',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
