# Generated by Django 2.2.15 on 2020-08-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200811_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='novote',
        ),
    ]
