# Generated by Django 2.2.15 on 2020-08-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
